version: '3.7'

services:
  app:
    build: .
    container_name: dropshipping_app
    ports:
      - '3333:3333'
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: dropshipping_db
    volumes:
      - .:/app
    links:
      - db:database
    depends_on:
      - db
  db:
    image: mysql:5.7.35
    container_name: dropshipping_database
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: dropshipping_db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: dropshipping
      MYSQL_PASSWORD: dropshipping
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
